//HEADER Const
export const  TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const  TOGGLE_USER_DROP_DOWN_HIDDEN = 'TOGGLE_USER_DROP_DOWN_HIDDEN';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
