export const ADD_MORE_BUTTON = 'ADD_MORE_BUTTON';
export const SUB_MORE_BUTTON = 'SUB_MORE_BUTTON';
export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS';
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const REDUCE_CART_ITEM = 'REDUCE_CART_ITEM';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
export const PLACE_ORDERS_SUCCESS = 'PLACE_ORDERS_SUCCESS';
export const PLACE_ORDER_FAILS = 'PLACE_ORDER_FAILS';

