// Auth Const
// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const  SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE'
export const  SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE'
export const LOGOUT = 'LOGOUT';
export const USER_LOADING = 'USER_LOADING'
export const CREATE_PERSONAL_PROFILE_SUCCESS = 'CREATE_PERSONAL_PROFILE_SUCCESS';
export const CREATE_PERSONAL_PROFILE_FAIL = 'CREATE_PERSONAL_PROFILE_FAIL';
export const FETCH_PERSONAL_PROFILE_SUCCESS = 'FETCH_PERSONAL_PROFILE_SUCCESS';
export const FETCH_PERSONAL_PROFILE_FAIL = 'FETCH_PERSONAL_PROFILE_FAIL';
export const UPDATE_PERSONAL_PROFILE_SUCCESS = 'UPDATE_PERSONAL_PROFILE_SUCCESS';
export const UPDATE_PERSONAL_PROFILE_FAIL = 'UPDATE_PERSONAL_PROFILE_FAIL';
export const UPDATE_COMPANY_PROFILE_SUCCESS = 'UPDATE_COMPANY_PROFILE_SUCCESS';
export const UPDATE_COMPANY_PROFILE_FAIL = 'UPDATE_COMPANY_PROFILE_FAIL';
export const CREATE_COMPANY_PROFILE_SUCCESS = 'CREATE_COMPANY_PROFILE_SUCCESS';
export const CREATE_COMPANY_PROFILE_FAIL = 'CREATE_COMPANY_PROFILE_FAIL';
export const FETCH_COMPANY_PROFILE_SUCCESS = 'FETCH_COMPANY_PROFILE_SUCCESS';
export const FETCH_COMPANY_PROFILE_FAIL = 'FETCH_COMPANY_PROFILE_FAIL';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'


// billing address
export const CREATE_BILLING_ADDRESS_SUCCESS = 'CREATE_BILLING_ADDRESS_SUCCESS';
export const CREATE_BILLING_ADDRESS_FAILS = 'CREATE_BILLING_ADDRESS_FAILS';
export const FETCH_BILLING_ADDRESS_SUCCESS = 'FETCH_BILLING_ADDRESS_SUCCESS';
export const FETCH_BILLING_ADDRESS_FAILS = 'FETCH_BILLING_ADDRESS_FAILS';
export const UPDATE_BILLING_ADDRESS_SUCCESS = 'UPDATE_BILLING_ADDRESS_SUCCESS';
export const UPDATE_BILLING_ADDRESS_FAILS = 'UPDATE_BILLING_ADDRESS_FAILS';
export const GET_SINGLE_BILLING_ADDRESS_SUCCESS = 'GET_SINGLE_BILLING_ADDRESS_SUCCESS';
export const GET_SINGLE_BILLING_ADDRESS_FAILS = 'GET_SINGLE_BILLING_ADDRESS_FAILS';

// shipping address
export const CREATE_SHIPPING_ADDRESS_SUCCESS = 'CREATE_SHIPPING_ADDRESS_SUCCESS';
export const CREATE_SHIPPING_ADDRESS_FAILS = 'CREATE_SHIPPING_ADDRESS_FAILS';
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = 'UPDATE_SHIPPING_ADDRESS_SUCCESS';
export const UPDATE_SHIPPING_ADDRESS_FAILS = 'UPDATE_SHIPPING_ADDRESS_FAILS';
export const FETCH_SHIPPING_ADDRESS_SUCCESS = 'FETCH_SHIPPING_ADDRESS_SUCCESS';
export const FETCH_SHIPPING_ADDRESS_FAILS = 'FETCH_SHIPPING_ADDRESS_FAILS';
export const GET_SINGLE_SHIPPING_ADDRESS_SUCCESS = 'GET_SINGLE_SHIPPING_ADDRESS_SUCCESS';
export const GET_SINGLE_SHIPPING_ADDRESS_FAILS = 'GET_SINGLE_SHIPPING_ADDRESS_FAILS';
export const SHOW_FORM = 'SHOW_FORM';
